IFMD-59 Vertical slice architecture folder structure
mrmilu/react.base pull request #49
Opened 2024-09-26 11:50 UTC by arnaugomez

Redo folder structure to accommodate to the new Vertical Slice Architecture

There are too many changes, so my suggestion would be to checkout to the PR branch and see if everything is allright.

2024-09-26 14:32 UTC, Javimtib92 commented
The folders you named as `ui` should be named `presentation` instead, for consistency among our base projects.

Other than that LGTM 👍

2024-09-27 06:59 UTC, Anullos requested changes

2024-09-27 06:59 UTC, Anullos commented on src/shared/presentation/providers/user.provider.ts
>  import { createStore, useStore } from "zustand";
Siento comentar tan tarde, pero renombra la carpeta de providers por la de states, en states entra tanto providers, controllers, notifiers, etc. states lo engloba, si luego tienes un controller no tiene sentido meterlo en una carpeta de providers, pero si en la de states al igual que los providers.

2024-09-27 07:26 UTC, Javimtib92 commented on src/shared/presentation/providers/user.provider.ts
>  import { createStore, useStore } from "zustand";
Los `controller` no van en` application`? Dani inicialmente estaba estructurado con la carpeta de providers y yo lo veo bien así, tu que ventaja le ves? si quieres states o stores puedes separarlo.

2024-09-27 07:28 UTC, Anullos commented on src/shared/presentation/providers/user.provider.ts
>  import { createStore, useStore } from "zustand";
los controladores son parte del componente en si de la ui, es como un state, no debería ir en la capa de application

2024-09-27 07:31 UTC, Anullos approved these changes
hacerlo como diga Javier

2024-09-27 07:46 UTC, Javimtib92 commented on src/shared/presentation/providers/user.provider.ts
>  import { createStore, useStore } from "zustand";
Es cierto que los controllers van en `presentation` me he equivocado. Dicho esto, inicialmente en la documentación teníamos que los providers van a providers, y así se ha hecho en el cambio de arquitectura del proyecto de NextJS.

Bloquear este PR pidiendo un cambio de última hora en la arquitectura que no se ha hablado con el resto del equipo me parece que no procede, eso es todo.

2024-09-27 07:46 UTC, Javimtib92 commented
> hacerlo como diga Javier

Este comentario me parece fuera de lugar.

2024-09-27 08:19 UTC, Javimtib92 approved these changes

2024-09-27 11:45 UTC, merged